name: Update README with Google Scholar Publications

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install scholarly

      - name: Fetch Publications from Google Scholar
        run: |
          python fetch_publications.py

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.STARS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote remove origin
          git remote add origin https://${USERNAME}:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git commit -am "Updated recent publications" || echo "No changes to commit"
          git push origin main --force
